"""Third

Revision ID: 6c791ca8a534
Revises: 19213204ffbc
Create Date: 2022-01-02 11:40:06.971860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c791ca8a534'
down_revision = '19213204ffbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
